<<<<<<< HEAD
spring:
  profiles:
    active:dev

mybatis:
  typeAliasesPackage:com.xdd.entity
  mapperLocations:classpath:mapper/*.xml

spring:
  profiles:dev
  datasource:
    url:jdbc:mysql://localhost:3306/test
    username:root
    password:root
=======
spring:
  profiles:
    active:dev

mybatis:
  typeAliasesPackage:com.xdd.entity
  mapperLocations:classpath:mapper/*.xml

spring:
  profiles:dev
  datasource:
    url:jdbc:mysql://localhost:3306/test
    username:root
    password:root
>>>>>>> 20180829 commit;
    driver-class-name: com.mysql.jdbc.Driver